#!/usr/bin/env bash
kubectl delete -f /root/.jenkins/workspace/app-api/cloud-app/app-api/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-api/cloud-app/app-api/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-financial/cloud-app/app-financial/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-financial/cloud-app/app-financial/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-im/cloud-app/app-im/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-im/cloud-app/app-im/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-learn/cloud-app/app-learn/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-learn/cloud-app/app-learn/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-member/cloud-app/app-member/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-member/cloud-app/app-member/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-order/cloud-app/app-order/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-order/cloud-app/app-order/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-pay/cloud-app/app-pay/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-pay/cloud-app/app-pay/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-product/cloud-app/app-product/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-product/cloud-app/app-product/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-rule/cloud-app/app-rule/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-rule/cloud-app/app-rule/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-store/cloud-app/app-store/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-store/cloud-app/app-store/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-system/cloud-app/app-system/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-system/cloud-app/app-system/src/main/resources/deploy/yml/pro.yml
kubectl delete -f /root/.jenkins/workspace/app-umeng/cloud-app/app-umeng/src/main/resources/deploy/yml/pro.yml
kubectl apply -f /root/.jenkins/workspace/app-umeng/cloud-app/app-umeng/src/main/resources/deploy/yml/pro.yml
